# Generated by Django 6.0.1 on 2026-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsavvy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsavvymodels',
            name='birthdate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
