# Generated by Django 6.0.1 on 2026-01-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsavvy_app', '0003_alter_techsavvymodels_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsavvymodels',
            name='middlename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
