# Generated by Django 6.0 on 2025-12-28 04:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delgar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='delgar/products/'),
        ),
    ]
