# Generated by Django 5.2.7 on 2026-03-01 16:33

import django_jsonform.models.fields
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricsplus', '0002_fileuploadmodel_itemlistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPostingCMSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('authors', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filters', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('descriptions', models.TextField(blank=True, default='', null=True)),
                ('approval_status', models.CharField(blank=True, default='verified', max_length=50, null=True)),
                ('links', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('files', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('logs', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='fabricsplus/assets/'),
        ),
    ]
