# Generated by Django 6.0.1 on 2026-01-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsavvy_app', '0002_techsavvymodels_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techsavvymodels',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='bonusPoints',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='gcashPoints',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='honorariumPoints',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='idNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='mobile',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='numberOfProjects',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='voucherPoints',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techsavvymodels',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
