# Generated by Django 5.2.7 on 2026-01-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsavvy_app', '0004_techsavvymodels_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsavvymodels',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
