# Generated by Django 6.0 on 2025-12-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('business', models.CharField(blank=True, max_length=255)),
                ('interest', models.CharField(choices=[('website', 'Website + Management'), ('social', 'Social Media Management'), ('both', 'Website + Social Media')], max_length=20)),
                ('message', models.TextField()),
                ('billing_option', models.CharField(choices=[('one-time', 'One-time'), ('split', 'Split (3 months)')], default='one-time', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
