# Generated by Django 5.2.7 on 2026-02-18 10:27

import django_jsonform.models.fields
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPostingCMSModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('authors', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filters', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('event_date', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('descriptions', models.TextField(blank=True, default='', null=True)),
                ('approval_status', models.CharField(blank=True, default='verified', max_length=50, null=True)),
                ('links', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('files', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('logs', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='aptitude/assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
