# Generated by Django 5.2.7 on 2026-02-19 07:33

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapostingcmsmodel',
            name='seat_availability',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapostingcmsmodel',
            name='seat_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datapostingcmsmodel',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
