# Generated by Django 5.2.7 on 2026-03-02 12:13

import django_jsonform.models.fields
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0002_datapostingcmsmodel_seat_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fullname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('position_application', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('years_of_experience', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('portfolio_url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tell_us_about_yourself_experience', models.TextField(blank=True, default='', null=True)),
                ('resume', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('logs', django_jsonform.models.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileUploadResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='aptitude/resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
