# Generated by Django 5.2.7 on 2026-03-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0003_careersmodel_fileuploadresumemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareersModel',
            new_name='AECareersModel',
        ),
        migrations.RenameModel(
            old_name='FileUploadResumeModel',
            new_name='AEFileUploadResumeModel',
        ),
    ]
