# Generated by Django 6.0.3 on 2026-03-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0004_techsavvymodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechsavvyModels',
            new_name='TechsavvyMembers',
        ),
    ]
