# Generated by Django 6.0.3 on 2026-03-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0005_rename_techsavvymodels_to_techsavvymembers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
