# Generated by Django 6.0.3 on 2026-03-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0006_alter_cmsitem_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('duration', models.CharField(blank=True, default='', help_text='e.g. "4 weeks"', max_length=100)),
                ('instructor', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=list, help_text='Enrollment / resource links')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='', help_text='e.g. Web, Mobile, IoT', max_length=100)),
                ('image', models.URLField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('team_members', models.JSONField(blank=True, default=list, help_text='List of contributor names')),
                ('links', models.JSONField(blank=True, default=list, help_text='Demo / repo links')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
