# Generated by Django 6.0.3 on 2026-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0007_course_featuredproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsitem',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
