# Generated by Django 6.0.3 on 2026-03-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0008_alter_cmsitem_approval_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='FeaturedProject',
        ),
    ]
