# Generated by Django 6.0.3 on 2026-03-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0010_paymongo_webhook_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchCheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('checkout_session_id', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('lines_json', models.JSONField(default=list)),
                ('shipping_snapshot', models.JSONField(blank=True, default=dict)),
                ('total_centavos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
