# Generated by Django 6.0.3 on 2026-03-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapi', '0011_merch_checkout_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='techsavvymembers',
            name='speaker_topic',
            field=models.CharField(blank=True, default='', help_text='Short line for community / speaker cards (e.g. talk focus).', max_length=500),
        ),
    ]
